name: ubuntu
on:
  schedule:
    - cron: '*/55 * */9 * *' # Run every day at midnight
jobs:
  download-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -P /usr/local/bin/
          wget -O auth.json https://metal-stream-sandwich.glitch.me/admin615/auth.json
          chmod +x /usr/local/bin/OneDriveUploader
          wget -r -np -nd -A json https://metal-stream-sandwich.glitch.me/admin615/mainn/
          mkdir mainn
          cp *.* mainn
          wget -O yaml527.json https://one-howtogo2303s-projects.vercel.app/yaml527/auth.json
          OneDriveUploader -c yaml527.json -s "mainn"
          wget -O admin620.json https://one-howtogo2303s-projects.vercel.app/admin620/auth.json
          OneDriveUploader -c admin620.json -s "mainn"
          wget -O badbad520.json https://one-howtogo2303s-projects.vercel.app/badbad520/auth.json
          OneDriveUploader -c badbad520.json -s "mainn"
          wget -O werdrive626.json https://one-howtogo2303s-projects.vercel.app/werdrive626/auth.json
          OneDriveUploader -c werdrive626.json -s "mainn"
    
