name: ubunt-try
on: [push, workflow_dispatch]
jobs:
  download-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -P /usr/local/bin/
          wget -O auth.json https://metal-stream-sandwich.glitch.me/admin615/auth.json
          chmod +x /usr/local/bin/OneDriveUploader
          
          
          for i in {1..1}; do wget -nH -m --ftp-user=amer6677 --ftp-password=123456123456aQ### ftp://ftp-amer6677.alwaysdata.net/www/230117/*;sleep 5; done;
          for i in {1..1}; do wget -nH -m --ftp-user=amer6677 --ftp-password=123456123456aQ### ftp://ftp-amer6677.alwaysdata.net/www/230118/*;sleep 5; done;
          for i in {1..1}; do wget -nH -m --ftp-user=amer6677 --ftp-password=123456123456aQ### ftp://ftp-amer6677.alwaysdata.net/www/230119/*;sleep 5; done;
          for i in {1..1}; do wget -nH -m --ftp-user=amer6677 --ftp-password=123456123456aQ### ftp://ftp-amer6677.alwaysdata.net/www/230120/*;sleep 5; done;
          for i in {1..1}; do wget -nH -m --ftp-user=amer6677 --ftp-password=123456123456aQ### ftp://ftp-amer6677.alwaysdata.net/www/230121/*;sleep 5; done;
          
          curl -sLkO https://raw.githubusercontent.com/howtogo2303/0127/main/.github/workflows/drive333.sh
          bash drive333.sh
          
          OneDriveUploader -c /home/runner/work/0127/0127/bftyuip611.json -s "/home/runner/work/0127"
          OneDriveUploader -c /home/runner/work/0127/0127/dtyiop709.json -s "/home/runner/work/0127"
          OneDriveUploader -c /home/runner/work/0127/0127/tyvyuiop709.json -s "/home/runner/work/0127"
          OneDriveUploader -c /home/runner/work/0127/0127/gothyy610.json -s "/home/runner/work/0127"
          OneDriveUploader -c /home/runner/work/0127/0127/northtty612.json -s "/home/runner/work/0127"
          OneDriveUploader -c /home/runner/work/0127/0127/amertty612.json -s "/home/runner/work/0127"
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -P /usr/local/bin/
          
