name: ubunt-try
on: [push, workflow_dispatch]
jobs:
  download-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -P /usr/local/bin/
          wget -O auth.json https://metal-stream-sandwich.glitch.me/admin615/auth.json
          chmod +x /usr/local/bin/OneDriveUploader
          for i in {1..1}; do wget -nH -m --ftp-user=amer6677 --ftp-password=123456123456aQ### ftp://ftp-amer6677.alwaysdata.net/www/230117/*;sleep 5; done;
          pwd
          cp /home/runner/work/0127/0127/www/230117/* ./

          
          curl -sLkO https://raw.githubusercontent.com/howtogo2303/0127/main/.github/workflows/drive111.sh
          bash drive111.sh
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -P /usr/local/bin/
          wget -O auth.json https://metal-stream-sandwich.glitch.me/admin615/auth.json
          chmod +x /usr/local/bin/OneDriveUploader
          for i in {1..1}; do wget -nH -m --ftp-user=amer6677 --ftp-password=123456123456aQ### ftp://ftp-amer6677.alwaysdata.net/www/230117/*;sleep 5; done;
          for i in {1..1}; do wget -nH -m --ftp-user=amer6677 --ftp-password=123456123456aQ### ftp://ftp-amer6677.alwaysdata.net/www/230118/*;sleep 5; done;
          for i in {1..1}; do wget -nH -m --ftp-user=amer6677 --ftp-password=123456123456aQ### ftp://ftp-amer6677.alwaysdata.net/www/230119/*;sleep 5; done;
          for i in {1..1}; do wget -nH -m --ftp-user=amer6677 --ftp-password=123456123456aQ### ftp://ftp-amer6677.alwaysdata.net/www/230120/*;sleep 5; done;
          for i in {1..1}; do wget -nH -m --ftp-user=amer6677 --ftp-password=123456123456aQ### ftp://ftp-amer6677.alwaysdata.net/www/230121/*;sleep 5; done;
          cp /www/230118/* ./
          curl -sLkO https://raw.githubusercontent.com/howtogo2303/0127/main/.github/workflows/drive11
          bash drive11
